import {
  ClearSkyDay,
  ClearSkyNight,
  ClearSkyPolarTwilight,
  Cloudy,
  FairDay,
  FairNight,
  FairPolarTwilight,
  Fog,
  HeavyRain,
  HeavyRainAndThunder,
  HeavyRainShowersDay,
  HeavyRainShowersNight,
  HeavyRainShowersPolarTwilight,
  HeavyRainShowersAndThunderDay,
  HeavyRainShowersAndThunderNight,
  HeavyRainShowersAndThunderPolarTwilight,
  HeavySleet,
  HeavySleetAndThunder,
  HeavySleetShowersDay,
  HeavySleetShowersNight,
  HeavySleetShowersPolarTwilight,
  HeavySleetShowersAndThunderDay,
  HeavySleetShowersAndThunderNight,
  HeavySleetShowersAndThunderPolarTwilight,
  HeavySnow,
  HeavySnowAndThunder,
  HeavySnowShowersDay,
  HeavySnowShowersNight,
  HeavySnowShowersPolarTwilight,
  HeavySnowShowersAndThunderDay,
  HeavySnowShowersAndThunderNight,
  HeavySnowShowersAndThunderPolarTwilight,
  LightRain,
  LightRainAndThunder,
  LightRainShowersDay,
  LightRainShowersNight,
  LightRainShowersPolarTwilight,
  LightRainShowersAndThunderDay,
  LightRainShowersAndThunderNight,
  LightRainShowersAndThunderPolarTwilight,
  LightSleet,
  LightSleetAndThunder,
  LightSleetShowersDay,
  LightSleetShowersNight,
  LightSleetShowersPolarTwilight,
  LightSnow,
  LightSnowAndThunder,
  LightSnowShowersDay,
  LightSnowShowersNight,
  LightSnowShowersPolarTwilight,
  LightSleetShowersAndThunderDay,
  LightSleetShowersAndThunderNight,
  LightSleetShowersAndThunderPolarTwilight,
  LightSnowShowersAndThunderDay,
  LightSnowShowersAndThunderNight,
  LightSnowShowersAndThunderPolarTwilight,
  PartlyCloudyDay,
  PartlyCloudyNight,
  PartlyCloudyPolarTwilight,
  Rain,
  RainAndThunder,
  RainShowersDay,
  RainShowersNight,
  RainShowersPolarTwilight,
  RainShowersAndThunderDay,
  RainShowersAndThunderNight,
  RainShowersAndThunderPolarTwilight,
  Sleet,
  SleetAndThunder,
  SleetShowersDay,
  SleetShowersNight,
  SleetShowersPolarTwilight,
  SleetShowersAndThunderDay,
  SleetShowersAndThunderNight,
  SleetShowersAndThunderPolarTwilight,
  Snow,
  SnowAndThunder,
  SnowShowersDay,
  SnowShowersNight,
  SnowShowersPolarTwilight,
  SnowShowersAndThunderDay,
  SnowShowersAndThunderNight,
  SnowShowersAndThunderPolarTwilight,
} from '@patrikhultgren/react-weather-icons'
import { IWeatherIcons } from 'utils/types'

const weatherIcons: IWeatherIcons = {
  clearsky_day: { Icon: ClearSkyDay, title: 'Soligt' },
  clearsky_night: { Icon: ClearSkyNight, title: 'Klar natt' },
  clearsky_polartwilight: { Icon: ClearSkyPolarTwilight, title: 'Klar natt' },
  cloudy: { Icon: Cloudy, title: 'Monligt' },
  fair_day: { Icon: FairDay, title: 'Delvis monligt' },
  fair_night: { Icon: FairNight, title: 'Delvis monligt' },
  fair_polartwilight: { Icon: FairPolarTwilight, title: 'Delvis monligt' },
  fog: { Icon: Fog, title: 'Dimma' },
  heavyrain: { Icon: HeavyRain, title: 'Mycket regn' },
  heavyrainandthunder: {
    Icon: HeavyRainAndThunder,
    title: 'Mycket regn och åska',
  },
  heavyrainshowers_day: {
    Icon: HeavyRainShowersDay,
    title: 'Kraftiga regnskurar',
  },
  heavyrainshowers_night: {
    Icon: HeavyRainShowersNight,
    title: 'Kraftiga regnskurar',
  },
  heavyrainshowers_polartwilight: {
    Icon: HeavyRainShowersPolarTwilight,
    title: 'Kraftiga regnskurar',
  },
  heavyrainshowersandthunder_day: {
    Icon: HeavyRainShowersAndThunderDay,
    title: 'Mycket regn och åska',
  },
  heavyrainshowersandthunder_night: {
    Icon: HeavyRainShowersAndThunderNight,
    title: 'Mycket regn och åska',
  },
  heavyrainshowersandthunder_polartwilight: {
    Icon: HeavyRainShowersAndThunderPolarTwilight,
    title: 'Mycket regn och åska',
  },
  heavysleet: { Icon: HeavySleet, title: 'Kraftigt snöblandat regn' },
  heavysleetandthunder: {
    Icon: HeavySleetAndThunder,
    title: 'Kraftigt snöblandat regn och åska',
  },
  heavysleetshowers_day: {
    Icon: HeavySleetShowersDay,
    title: 'Kraftiga snöblandade regnskurar',
  },
  heavysleetshowers_night: {
    Icon: HeavySleetShowersNight,
    title: 'Kraftiga snöblandade regnskurar',
  },
  heavysleetshowers_polartwilight: {
    Icon: HeavySleetShowersPolarTwilight,
    title: 'Kraftiga snöblandade regnskurar',
  },
  heavysleetshowersandthunder_day: {
    Icon: HeavySleetShowersAndThunderDay,
    title: 'Kraftiga snöblandade regnskurar och åska',
  },
  heavysleetshowersandthunder_night: {
    Icon: HeavySleetShowersAndThunderNight,
    title: 'Kraftiga snöblandade regnskurar och åska',
  },
  heavysleetshowersandthunder_polartwilight: {
    Icon: HeavySleetShowersAndThunderPolarTwilight,
    title: 'Kraftiga snöblandade regnskurar och åska',
  },
  heavysnow: { Icon: HeavySnow, title: 'Kraftigt snöfall' },
  heavysnowandthunder: {
    Icon: HeavySnowAndThunder,
    title: 'Kraftigt snöfall och åska',
  },
  heavysnowshowers_day: {
    Icon: HeavySnowShowersDay,
    title: 'Kraftigt snöfall',
  },
  heavysnowshowers_night: {
    Icon: HeavySnowShowersNight,
    title: 'Kraftigt snöfall',
  },
  heavysnowshowers_polartwilight: {
    Icon: HeavySnowShowersPolarTwilight,
    title: 'Kraftigt snöfall',
  },
  heavysnowshowersandthunder_day: {
    Icon: HeavySnowShowersAndThunderDay,
    title: 'Kraftigt snöfall och åska',
  },
  heavysnowshowersandthunder_night: {
    Icon: HeavySnowShowersAndThunderNight,
    title: 'Kraftigt snöfall och åska',
  },
  heavysnowshowersandthunder_polartwilight: {
    Icon: HeavySnowShowersAndThunderPolarTwilight,
    title: 'Kraftigt snöfall och åska',
  },
  lightrain: { Icon: LightRain, title: 'Duggregn' },
  lightrainandthunder: {
    Icon: LightRainAndThunder,
    title: 'Duggregn och åska',
  },
  lightrainshowers_day: { Icon: LightRainShowersDay, title: 'Duggregn' },
  lightrainshowers_night: { Icon: LightRainShowersNight, title: 'Duggregn' },
  lightrainshowers_polartwilight: {
    Icon: LightRainShowersPolarTwilight,
    title: 'Duggregn',
  },
  lightrainshowersandthunder_day: {
    Icon: LightRainShowersAndThunderDay,
    title: 'Duggregn och åska',
  },
  lightrainshowersandthunder_night: {
    Icon: LightRainShowersAndThunderNight,
    title: 'Duggregn och åska',
  },
  lightrainshowersandthunder_polartwilight: {
    Icon: LightRainShowersAndThunderPolarTwilight,
    title: 'Duggregn och åska',
  },
  lightsleet: { Icon: LightSleet, title: 'Lätt snöblandat regn' },
  lightsleetandthunder: {
    Icon: LightSleetAndThunder,
    title: 'Lätt snöblandat regn och åska',
  },
  lightsleetshowers_day: {
    Icon: LightSleetShowersDay,
    title: 'Lätt snöblandat regn',
  },
  lightsleetshowers_night: {
    Icon: LightSleetShowersNight,
    title: 'Lätt snöblandat regn',
  },
  lightsleetshowers_polartwilight: {
    Icon: LightSleetShowersPolarTwilight,
    title: 'Lätt snöblandat regn',
  },
  lightsnow: { Icon: LightSnow, title: 'Lite snö' },
  lightsnowandthunder: {
    Icon: LightSnowAndThunder,
    title: 'Lite snö och åska',
  },
  lightsnowshowers_day: { Icon: LightSnowShowersDay, title: 'Lite snö' },
  lightsnowshowers_night: { Icon: LightSnowShowersNight, title: 'Lite snö' },
  lightsnowshowers_polartwilight: {
    Icon: LightSnowShowersPolarTwilight,
    title: 'Lite snö',
  },
  lightssleetshowersandthunder_day: {
    Icon: LightSleetShowersAndThunderDay,
    title: 'Lite snöblandade regnskurar och åska',
  },
  lightssleetshowersandthunder_night: {
    Icon: LightSleetShowersAndThunderNight,
    title: 'Lite snöblandade regnskurar och åska',
  },
  lightssleetshowersandthunder_polartwilight: {
    Icon: LightSleetShowersAndThunderPolarTwilight,
    title: 'Lite snöblandade regnskurar och åska',
  },
  lightssnowshowersandthunder_day: {
    Icon: LightSnowShowersAndThunderDay,
    title: 'Lite snö och åska',
  },
  lightssnowshowersandthunder_night: {
    Icon: LightSnowShowersAndThunderNight,
    title: 'Lite snö och åska',
  },
  lightssnowshowersandthunder_polartwilight: {
    Icon: LightSnowShowersAndThunderPolarTwilight,
    title: 'Lite snö och åska',
  },
  partlycloudy_day: { Icon: PartlyCloudyDay, title: 'Delvis monligt' },
  partlycloudy_night: { Icon: PartlyCloudyNight, title: 'Delvis monligt' },
  partlycloudy_polartwilight: { Icon: PartlyCloudyPolarTwilight, title: '' },
  rain: { Icon: Rain, title: 'Regn' },
  rainandthunder: { Icon: RainAndThunder, title: 'Regn och åska' },
  rainshowers_day: { Icon: RainShowersDay, title: 'Regn och åska' },
  rainshowers_night: { Icon: RainShowersNight, title: 'Regnigt' },
  rainshowers_polartwilight: {
    Icon: RainShowersPolarTwilight,
    title: 'Regnskurar',
  },
  rainshowersandthunder_day: {
    Icon: RainShowersAndThunderDay,
    title: 'Regnskurar och åska',
  },
  rainshowersandthunder_night: {
    Icon: RainShowersAndThunderNight,
    title: 'Regnskurar och åska',
  },
  rainshowersandthunder_polartwilight: {
    Icon: RainShowersAndThunderPolarTwilight,
    title: 'Regnskurar och åska',
  },
  sleet: { Icon: Sleet, title: 'Snöblandet regn' },
  sleetandthunder: { Icon: SleetAndThunder, title: 'Snöblandet regn och åska' },
  sleetshowers_day: { Icon: SleetShowersDay, title: 'Snöblandet regn' },
  sleetshowers_night: { Icon: SleetShowersNight, title: 'Snöblandet regn' },
  sleetshowers_polartwilight: {
    Icon: SleetShowersPolarTwilight,
    title: 'Snöblandet regn',
  },
  sleetshowersandthunder_day: {
    Icon: SleetShowersAndThunderDay,
    title: 'Snöblandet regn och åska',
  },
  sleetshowersandthunder_night: {
    Icon: SleetShowersAndThunderNight,
    title: 'Snöblandet regn och åska',
  },
  sleetshowersandthunder_polartwilight: {
    Icon: SleetShowersAndThunderPolarTwilight,
    title: 'Snöblandet regn och åska',
  },
  snow: { Icon: Snow, title: 'Snö' },
  snowandthunder: { Icon: SnowAndThunder, title: 'Snö och åska' },
  snowshowers_day: { Icon: SnowShowersDay, title: 'Mycket snö' },
  snowshowers_night: { Icon: SnowShowersNight, title: 'Mycket snö' },
  snowshowers_polartwilight: {
    Icon: SnowShowersPolarTwilight,
    title: 'Mycket snö',
  },
  snowshowersandthunder_day: {
    Icon: SnowShowersAndThunderDay,
    title: 'Mycket snö och åska',
  },
  snowshowersandthunder_night: {
    Icon: SnowShowersAndThunderNight,
    title: 'Mycket snö och åska',
  },
  snowshowersandthunder_polartwilight: {
    Icon: SnowShowersAndThunderPolarTwilight,
    title: 'Mycket snö och åska',
  },
}

export default weatherIcons
