import {
  ClearSkyDay,
  ClearSkyNight,
  ClearSkyPolarTwilight,
  Cloudy,
  FairDay,
  FairNight,
  FairPolarTwilight,
  Fog,
  HeavyRain,
  HeavyRainAndThunder,
  HeavyRainShowersDay,
  HeavyRainShowersNight,
  HeavyRainShowersPolarTwilight,
  HeavyRainShowersAndThunderDay,
  HeavyRainShowersAndThunderNight,
  HeavyRainShowersAndThunderPolarTwilight,
  HeavySleet,
  HeavySleetAndThunder,
  HeavySleetShowersDay,
  HeavySleetShowersNight,
  HeavySleetShowersPolarTwilight,
  HeavySleetShowersAndThunderDay,
  HeavySleetShowersAndThunderNight,
  HeavySleetShowersAndThunderPolarTwilight,
  HeavySnow,
  HeavySnowAndThunder,
  HeavySnowShowersDay,
  HeavySnowShowersNight,
  HeavySnowShowersPolarTwilight,
  HeavySnowShowersAndThunderDay,
  HeavySnowShowersAndThunderNight,
  HeavySnowShowersAndThunderPolarTwilight,
  LightRain,
  LightRainAndThunder,
  LightRainShowersDay,
  LightRainShowersNight,
  LightRainShowersPolarTwilight,
  LightRainShowersAndThunderDay,
  LightRainShowersAndThunderNight,
  LightRainShowersAndThunderPolarTwilight,
  LightSleet,
  LightSleetAndThunder,
  LightSleetShowersDay,
  LightSleetShowersNight,
  LightSleetShowersPolarTwilight,
  LightSnow,
  LightSnowAndThunder,
  LightSnowShowersDay,
  LightSnowShowersNight,
  LightSnowShowersPolarTwilight,
  LightSleetShowersAndThunderDay,
  LightSleetShowersAndThunderNight,
  LightSleetShowersAndThunderPolarTwilight,
  LightSnowShowersAndThunderDay,
  LightSnowShowersAndThunderNight,
  LightSnowShowersAndThunderPolarTwilight,
  PartlyCloudyDay,
  PartlyCloudyNight,
  PartlyCloudyPolarTwilight,
  Rain,
  RainAndThunder,
  RainShowersDay,
  RainShowersNight,
  RainShowersPolarTwilight,
  RainShowersAndThunderDay,
  RainShowersAndThunderNight,
  RainShowersAndThunderPolarTwilight,
  Sleet,
  SleetAndThunder,
  SleetShowersDay,
  SleetShowersNight,
  SleetShowersPolarTwilight,
  SleetShowersAndThunderDay,
  SleetShowersAndThunderNight,
  SleetShowersAndThunderPolarTwilight,
  Snow,
  SnowAndThunder,
  SnowShowersDay,
  SnowShowersNight,
  SnowShowersPolarTwilight,
  SnowShowersAndThunderDay,
  SnowShowersAndThunderNight,
  SnowShowersAndThunderPolarTwilight,
} from '@patrikhultgren/react-weather-icons'

const weatherIcons: { [key: string]: { Icon: any; title: string } } = {
  clearsky_day: { Icon: ClearSkyDay, title: 'Soligt' },
  clearsky_night: { Icon: ClearSkyNight, title: 'Klar natt' },
  clearsky_polartwilight: { Icon: ClearSkyPolarTwilight, title: 'Klar natt' },
  cloudy: { Icon: Cloudy, title: 'Monligt' },
  fair_day: { Icon: FairDay, title: 'Delvis monligt' },
  fair_night: { Icon: FairNight, title: 'Delvis monligt' },
  fair_polartwilight: { Icon: FairPolarTwilight, title: 'Delvis monligt' },
  fog: { Icon: Fog, title: 'Dimma' },
  heavyrain: { Icon: HeavyRain, title: 'Mycket regn' },
  heavyrainandthunder: {
    Icon: HeavyRainAndThunder,
    title: 'Mycket regn och åska',
  },
  heavyrainshowers_day: { Icon: HeavyRainShowersDay, title: '' },
  heavyrainshowers_night: { Icon: HeavyRainShowersNight, title: '' },
  heavyrainshowers_polartwilight: {
    Icon: HeavyRainShowersPolarTwilight,
    title: '',
  },
  heavyrainshowersandthunder_day: {
    Icon: HeavyRainShowersAndThunderDay,
    title: 'Mycket regn och åska',
  },
  heavyrainshowersandthunder_night: {
    Icon: HeavyRainShowersAndThunderNight,
    title: 'Mycket regn och åska',
  },
  heavyrainshowersandthunder_polartwilight: {
    Icon: HeavyRainShowersAndThunderPolarTwilight,
    title: 'Mycket regn och åska',
  },
  heavysleet: { Icon: HeavySleet, title: 'Mycket regn' },
  heavysleetandthunder: { Icon: HeavySleetAndThunder, title: '' },
  heavysleetshowers_day: { Icon: HeavySleetShowersDay, title: '' },
  heavysleetshowers_night: { Icon: HeavySleetShowersNight, title: '' },
  heavysleetshowers_polartwilight: {
    Icon: HeavySleetShowersPolarTwilight,
    title: 'Kraftiga snöskurar',
  },
  heavysleetshowersandthunder_day: {
    Icon: HeavySleetShowersAndThunderDay,
    title: '',
  },
  heavysleetshowersandthunder_night: {
    Icon: HeavySleetShowersAndThunderNight,
    title: '',
  },
  heavysleetshowersandthunder_polartwilight: {
    Icon: HeavySleetShowersAndThunderPolarTwilight,
    title: '',
  },
  heavysnow: { Icon: HeavySnow, title: '' },
  heavysnowandthunder: { Icon: HeavySnowAndThunder, title: '' },
  heavysnowshowers_day: { Icon: HeavySnowShowersDay, title: '' },
  heavysnowshowers_night: { Icon: HeavySnowShowersNight, title: '' },
  heavysnowshowers_polartwilight: {
    Icon: HeavySnowShowersPolarTwilight,
    title: '',
  },
  heavysnowshowersandthunder_day: {
    Icon: HeavySnowShowersAndThunderDay,
    title: '',
  },
  heavysnowshowersandthunder_night: {
    Icon: HeavySnowShowersAndThunderNight,
    title: '',
  },
  heavysnowshowersandthunder_polartwilight: {
    Icon: HeavySnowShowersAndThunderPolarTwilight,
    title: '',
  },
  lightrain: { Icon: LightRain, title: 'Duggregn' },
  lightrainandthunder: { Icon: LightRainAndThunder, title: '' },
  lightrainshowers_day: { Icon: LightRainShowersDay, title: '' },
  lightrainshowers_night: { Icon: LightRainShowersNight, title: '' },
  lightrainshowers_polartwilight: {
    Icon: LightRainShowersPolarTwilight,
    title: '',
  },
  lightrainshowersandthunder_day: {
    Icon: LightRainShowersAndThunderDay,
    title: '',
  },
  lightrainshowersandthunder_night: {
    Icon: LightRainShowersAndThunderNight,
    title: '',
  },
  lightrainshowersandthunder_polartwilight: {
    Icon: LightRainShowersAndThunderPolarTwilight,
    title: '',
  },
  lightsleet: { Icon: LightSleet, title: 'Lätt snöblandat regn' },
  lightsleetandthunder: { Icon: LightSleetAndThunder, title: '' },
  lightsleetshowers_day: { Icon: LightSleetShowersDay, title: '' },
  lightsleetshowers_night: { Icon: LightSleetShowersNight, title: '' },
  lightsleetshowers_polartwilight: {
    Icon: LightSleetShowersPolarTwilight,
    title: '',
  },
  lightsnow: { Icon: LightSnow, title: 'Lite snö' },
  lightsnowandthunder: { Icon: LightSnowAndThunder, title: '' },
  lightsnowshowers_day: { Icon: LightSnowShowersDay, title: '' },
  lightsnowshowers_night: { Icon: LightSnowShowersNight, title: '' },
  lightsnowshowers_polartwilight: {
    Icon: LightSnowShowersPolarTwilight,
    title: '',
  },
  lightssleetshowersandthunder_day: {
    Icon: LightSleetShowersAndThunderDay,
    title: '',
  },
  lightssleetshowersandthunder_night: {
    Icon: LightSleetShowersAndThunderNight,
    title: '',
  },
  lightssleetshowersandthunder_polartwilight: {
    Icon: LightSleetShowersAndThunderPolarTwilight,
    title: '',
  },
  lightssnowshowersandthunder_day: {
    Icon: LightSnowShowersAndThunderDay,
    title: '',
  },
  lightssnowshowersandthunder_night: {
    Icon: LightSnowShowersAndThunderNight,
    title: '',
  },
  lightssnowshowersandthunder_polartwilight: {
    Icon: LightSnowShowersAndThunderPolarTwilight,
    title: '',
  },
  partlycloudy_day: { Icon: PartlyCloudyDay, title: 'Delvis monligt' },
  partlycloudy_night: { Icon: PartlyCloudyNight, title: 'Delvis monligt' },
  partlycloudy_polartwilight: { Icon: PartlyCloudyPolarTwilight, title: '' },
  rain: { Icon: Rain, title: 'Regn' },
  rainandthunder: { Icon: RainAndThunder, title: '' },
  rainshowers_day: { Icon: RainShowersDay, title: '' },
  rainshowers_night: { Icon: RainShowersNight, title: 'Regnigt' },
  rainshowers_polartwilight: { Icon: RainShowersPolarTwilight, title: '' },
  rainshowersandthunder_day: { Icon: RainShowersAndThunderDay, title: '' },
  rainshowersandthunder_night: { Icon: RainShowersAndThunderNight, title: '' },
  rainshowersandthunder_polartwilight: {
    Icon: RainShowersAndThunderPolarTwilight,
    title: '',
  },
  sleet: { Icon: Sleet, title: 'Snöblandet regn' },
  sleetandthunder: { Icon: SleetAndThunder, title: '' },
  sleetshowers_day: { Icon: SleetShowersDay, title: '' },
  sleetshowers_night: { Icon: SleetShowersNight, title: '' },
  sleetshowers_polartwilight: { Icon: SleetShowersPolarTwilight, title: '' },
  sleetshowersandthunder_day: { Icon: SleetShowersAndThunderDay, title: '' },
  sleetshowersandthunder_night: {
    Icon: SleetShowersAndThunderNight,
    title: '',
  },
  sleetshowersandthunder_polartwilight: {
    Icon: SleetShowersAndThunderPolarTwilight,
    title: '',
  },
  snow: { Icon: Snow, title: 'Snö' },
  snowandthunder: { Icon: SnowAndThunder, title: '' },
  snowshowers_day: { Icon: SnowShowersDay, title: '' },
  snowshowers_night: { Icon: SnowShowersNight, title: '' },
  snowshowers_polartwilight: { Icon: SnowShowersPolarTwilight, title: '' },
  snowshowersandthunder_day: { Icon: SnowShowersAndThunderDay, title: '' },
  snowshowersandthunder_night: { Icon: SnowShowersAndThunderNight, title: '' },
  snowshowersandthunder_polartwilight: {
    Icon: SnowShowersAndThunderPolarTwilight,
    title: '',
  },
}

export default weatherIcons
