const weatherIconTitles: Record<string, string> = {
  clearsky_day: 'Soligt',
  clearsky_night: 'Klar natt',
  clearsky_polartwilight: 'Klar natt',
  cloudy: 'Monligt',
  fair_day: 'Delvis monligt',
  fair_night: 'Delvis monligt',
  fair_polartwilight: 'Delvis monligt',
  fog: 'Dimma',
  heavyrain: 'Mycket regn',
  heavyrainandthunder: 'Mycket regn och åska',
  heavyrainshowers_day: 'Kraftiga regnskurar',
  heavyrainshowers_night: 'Kraftiga regnskurar',
  heavyrainshowers_polartwilight: 'Kraftiga regnskurar',
  heavyrainshowersandthunder_day: 'Mycket regn och åska',
  heavyrainshowersandthunder_night: 'Mycket regn och åska',
  heavyrainshowersandthunder_polartwilight: 'Mycket regn och åska',
  heavysleet: 'Kraftigt snöblandat regn',
  heavysleetandthunder: 'Kraftigt snöblandat regn och åska',
  heavysleetshowers_day: 'Kraftiga snöblandade regnskurar',
  heavysleetshowers_night: 'Kraftiga snöblandade regnskurar',
  heavysleetshowers_polartwilight: 'Kraftiga snöblandade regnskurar',
  heavysleetshowersandthunder_day: 'Kraftiga snöblandade regnskurar och åska',
  heavysleetshowersandthunder_night: 'Kraftiga snöblandade regnskurar och åska',
  heavysleetshowersandthunder_polartwilight:
    'Kraftiga snöblandade regnskurar och åska',
  heavysnow: 'Kraftigt snöfall',
  heavysnowandthunder: 'Kraftigt snöfall och åska',
  heavysnowshowers_day: 'Kraftigt snöfall',
  heavysnowshowers_night: 'Kraftigt snöfall',
  heavysnowshowers_polartwilight: 'Kraftigt snöfall',
  heavysnowshowersandthunder_day: 'Kraftigt snöfall och åska',
  heavysnowshowersandthunder_night: 'Kraftigt snöfall och åska',
  heavysnowshowersandthunder_polartwilight: 'Kraftigt snöfall och åska',
  lightrain: 'Duggregn',
  lightrainandthunder: 'Duggregn och åska',
  lightrainshowers_day: 'Duggregn',
  lightrainshowers_night: 'Duggregn',
  lightrainshowers_polartwilight: 'Duggregn',
  lightrainshowersandthunder_day: 'Duggregn och åska',
  lightrainshowersandthunder_night: 'Duggregn och åska',
  lightrainshowersandthunder_polartwilight: 'Duggregn och åska',
  lightsleet: 'Lätt snöblandat regn',
  lightsleetandthunder: 'Lätt snöblandat regn och åska',
  lightsleetshowers_day: 'Lätt snöblandat regn',
  lightsleetshowers_night: 'Lätt snöblandat regn',
  lightsleetshowers_polartwilight: 'Lätt snöblandat regn',
  lightsnow: 'Lite snö',
  lightsnowandthunder: 'Lite snö och åska',
  lightsnowshowers_day: 'Lite snö',
  lightsnowshowers_night: 'Lite snö',
  lightsnowshowers_polartwilight: 'Lite snö',
  lightssleetshowersandthunder_day: 'Lite snöblandade regnskurar och åska',
  lightssleetshowersandthunder_night: 'Lite snöblandade regnskurar och åska',
  lightssleetshowersandthunder_polartwilight:
    'Lite snöblandade regnskurar och åska',
  lightssnowshowersandthunder_day: 'Lite snö och åska',
  lightssnowshowersandthunder_night: 'Lite snö och åska',
  lightssnowshowersandthunder_polartwilight: 'Lite snö och åska',
  partlycloudy_day: 'Delvis monligt',
  partlycloudy_night: 'Delvis monligt',
  partlycloudy_polartwilight: 'Delvis molnigt under polarskymning',
  rain: 'Regn',
  rainandthunder: 'Regn och åska',
  rainshowers_day: 'Regn och åska',
  rainshowers_night: 'Regnigt',
  rainshowers_polartwilight: 'Regnskurar',
  rainshowersandthunder_day: 'Regnskurar och åska',
  rainshowersandthunder_night: 'Regnskurar och åska',
  rainshowersandthunder_polartwilight: 'Regnskurar och åska',
  sleet: 'Snöblandet regn',
  sleetandthunder: 'Snöblandet regn och åska',
  sleetshowers_day: 'Snöblandet regn',
  sleetshowers_night: 'Snöblandet regn',
  sleetshowers_polartwilight: 'Snöblandet regn',
  sleetshowersandthunder_day: 'Snöblandet regn och åska',
  sleetshowersandthunder_night: 'Snöblandet regn och åska',
  sleetshowersandthunder_polartwilight: 'Snöblandet regn och åska',
  snow: 'Snö',
  snowandthunder: 'Snö och åska',
  snowshowers_day: 'Mycket snö',
  snowshowers_night: 'Mycket snö',
  snowshowers_polartwilight: 'Mycket snö',
  snowshowersandthunder_day: 'Mycket snö och åska',
  snowshowersandthunder_night: 'Mycket snö och åska',
  snowshowersandthunder_polartwilight: 'Mycket snö och åska',
}

export default weatherIconTitles
