import {
  ClearSkyDay,
  ClearSkyNight,
  ClearSkyPolarTwilight,
  Cloudy,
  FairDay,
  FairNight,
  FairPolarTwilight,
  Fog,
  HeavyRain,
  HeavyRainAndThunder,
  HeavyRainShowersDay,
  HeavyRainShowersNight,
  HeavyRainShowersPolarTwilight,
  HeavyRainShowersAndThunderDay,
  HeavyRainShowersAndThunderNight,
  HeavyRainShowersAndThunderPolarTwilight,
  HeavySleet,
  HeavySleetAndThunder,
  HeavySleetShowersDay,
  HeavySleetShowersNight,
  HeavySleetShowersPolarTwilight,
  HeavySleetShowersAndThunderDay,
  HeavySleetShowersAndThunderNight,
  HeavySleetShowersAndThunderPolarTwilight,
  HeavySnow,
  HeavySnowAndThunder,
  HeavySnowShowersDay,
  HeavySnowShowersNight,
  HeavySnowShowersPolarTwilight,
  HeavySnowShowersAndThunderDay,
  HeavySnowShowersAndThunderNight,
  HeavySnowShowersAndThunderPolarTwilight,
  LightRain,
  LightRainAndThunder,
  LightRainShowersDay,
  LightRainShowersNight,
  LightRainShowersPolarTwilight,
  LightRainShowersAndThunderDay,
  LightRainShowersAndThunderNight,
  LightRainShowersAndThunderPolarTwilight,
  LightSleet,
  LightSleetAndThunder,
  LightSleetShowersDay,
  LightSleetShowersNight,
  LightSleetShowersPolarTwilight,
  LightSnow,
  LightSnowAndThunder,
  LightSnowShowersDay,
  LightSnowShowersNight,
  LightSnowShowersPolarTwilight,
  LightSleetShowersAndThunderDay,
  LightSleetShowersAndThunderNight,
  LightSleetShowersAndThunderPolarTwilight,
  LightSnowShowersAndThunderDay,
  LightSnowShowersAndThunderNight,
  LightSnowShowersAndThunderPolarTwilight,
  PartlyCloudyDay,
  PartlyCloudyNight,
  PartlyCloudyPolarTwilight,
  Rain,
  RainAndThunder,
  RainShowersDay,
  RainShowersNight,
  RainShowersPolarTwilight,
  RainShowersAndThunderDay,
  RainShowersAndThunderNight,
  RainShowersAndThunderPolarTwilight,
  Sleet,
  SleetAndThunder,
  SleetShowersDay,
  SleetShowersNight,
  SleetShowersPolarTwilight,
  SleetShowersAndThunderDay,
  SleetShowersAndThunderNight,
  SleetShowersAndThunderPolarTwilight,
  Snow,
  SnowAndThunder,
  SnowShowersDay,
  SnowShowersNight,
  SnowShowersPolarTwilight,
  SnowShowersAndThunderDay,
  SnowShowersAndThunderNight,
  SnowShowersAndThunderPolarTwilight,
} from '@patrikhultgren/react-weather-icons'
import { IWeatherIcons } from 'utils/types'

const weatherIcons: IWeatherIcons = {
  clearsky_day: { Icon: ClearSkyDay, title: 'Soligt', id: '01d' },
  clearsky_night: { Icon: ClearSkyNight, title: 'Klar natt', id: '01n' },
  clearsky_polartwilight: {
    Icon: ClearSkyPolarTwilight,
    title: 'Klar natt',
    id: '01m',
  },
  cloudy: { Icon: Cloudy, title: 'Monligt', id: '04' },
  fair_day: { Icon: FairDay, title: 'Delvis monligt', id: '02d' },
  fair_night: { Icon: FairNight, title: 'Delvis monligt', id: '02n' },
  fair_polartwilight: {
    Icon: FairPolarTwilight,
    title: 'Delvis monligt',
    id: '02m',
  },
  fog: { Icon: Fog, title: 'Dimma', id: '15' },
  heavyrain: { Icon: HeavyRain, title: 'Mycket regn', id: '10' },
  heavyrainandthunder: {
    Icon: HeavyRainAndThunder,
    title: 'Mycket regn och åska',
    id: '11',
  },
  heavyrainshowers_day: {
    Icon: HeavyRainShowersDay,
    title: 'Kraftiga regnskurar',
    id: '41d',
  },
  heavyrainshowers_night: {
    Icon: HeavyRainShowersNight,
    title: 'Kraftiga regnskurar',
    id: '41n',
  },
  heavyrainshowers_polartwilight: {
    Icon: HeavyRainShowersPolarTwilight,
    title: 'Kraftiga regnskurar',
    id: '41m',
  },
  heavyrainshowersandthunder_day: {
    Icon: HeavyRainShowersAndThunderDay,
    title: 'Mycket regn och åska',
    id: '25d',
  },
  heavyrainshowersandthunder_night: {
    Icon: HeavyRainShowersAndThunderNight,
    title: 'Mycket regn och åska',
    id: '25n',
  },
  heavyrainshowersandthunder_polartwilight: {
    Icon: HeavyRainShowersAndThunderPolarTwilight,
    title: 'Mycket regn och åska',
    id: '25m',
  },
  heavysleet: { Icon: HeavySleet, title: 'Kraftigt snöblandat regn', id: '48' },
  heavysleetandthunder: {
    Icon: HeavySleetAndThunder,
    title: 'Kraftigt snöblandat regn och åska',
    id: '32',
  },
  heavysleetshowers_day: {
    Icon: HeavySleetShowersDay,
    title: 'Kraftiga snöblandade regnskurar',
    id: '43d',
  },
  heavysleetshowers_night: {
    Icon: HeavySleetShowersNight,
    title: 'Kraftiga snöblandade regnskurar',
    id: '43n',
  },
  heavysleetshowers_polartwilight: {
    Icon: HeavySleetShowersPolarTwilight,
    title: 'Kraftiga snöblandade regnskurar',
    id: '43m',
  },
  heavysleetshowersandthunder_day: {
    Icon: HeavySleetShowersAndThunderDay,
    title: 'Kraftiga snöblandade regnskurar och åska',
    id: '27d',
  },
  heavysleetshowersandthunder_night: {
    Icon: HeavySleetShowersAndThunderNight,
    title: 'Kraftiga snöblandade regnskurar och åska',
    id: '27n',
  },
  heavysleetshowersandthunder_polartwilight: {
    Icon: HeavySleetShowersAndThunderPolarTwilight,
    title: 'Kraftiga snöblandade regnskurar och åska',
    id: '27m',
  },
  heavysnow: { Icon: HeavySnow, title: 'Kraftigt snöfall', id: '50' },
  heavysnowandthunder: {
    Icon: HeavySnowAndThunder,
    title: 'Kraftigt snöfall och åska',
    id: '34',
  },
  heavysnowshowers_day: {
    Icon: HeavySnowShowersDay,
    title: 'Kraftigt snöfall',
    id: '45d',
  },
  heavysnowshowers_night: {
    Icon: HeavySnowShowersNight,
    title: 'Kraftigt snöfall',
    id: '45n',
  },
  heavysnowshowers_polartwilight: {
    Icon: HeavySnowShowersPolarTwilight,
    title: 'Kraftigt snöfall',
    id: '45m',
  },
  heavysnowshowersandthunder_day: {
    Icon: HeavySnowShowersAndThunderDay,
    title: 'Kraftigt snöfall och åska',
    id: '29d',
  },
  heavysnowshowersandthunder_night: {
    Icon: HeavySnowShowersAndThunderNight,
    title: 'Kraftigt snöfall och åska',
    id: '29n',
  },
  heavysnowshowersandthunder_polartwilight: {
    Icon: HeavySnowShowersAndThunderPolarTwilight,
    title: 'Kraftigt snöfall och åska',
    id: '29m',
  },
  lightrain: { Icon: LightRain, title: 'Duggregn', id: '46' },
  lightrainandthunder: {
    Icon: LightRainAndThunder,
    title: 'Duggregn och åska',
    id: '30',
  },
  lightrainshowers_day: {
    Icon: LightRainShowersDay,
    title: 'Duggregn',
    id: '40d',
  },
  lightrainshowers_night: {
    Icon: LightRainShowersNight,
    title: 'Duggregn',
    id: '40n',
  },
  lightrainshowers_polartwilight: {
    Icon: LightRainShowersPolarTwilight,
    title: 'Duggregn',
    id: '40m',
  },
  lightrainshowersandthunder_day: {
    Icon: LightRainShowersAndThunderDay,
    title: 'Duggregn och åska',
    id: '24d',
  },
  lightrainshowersandthunder_night: {
    Icon: LightRainShowersAndThunderNight,
    title: 'Duggregn och åska',
    id: '24n',
  },
  lightrainshowersandthunder_polartwilight: {
    Icon: LightRainShowersAndThunderPolarTwilight,
    title: 'Duggregn och åska',
    id: '24m',
  },
  lightsleet: { Icon: LightSleet, title: 'Lätt snöblandat regn', id: '47' },
  lightsleetandthunder: {
    Icon: LightSleetAndThunder,
    title: 'Lätt snöblandat regn och åska',
    id: '31',
  },
  lightsleetshowers_day: {
    Icon: LightSleetShowersDay,
    title: 'Lätt snöblandat regn',
    id: '42d',
  },
  lightsleetshowers_night: {
    Icon: LightSleetShowersNight,
    title: 'Lätt snöblandat regn',
    id: '42n',
  },
  lightsleetshowers_polartwilight: {
    Icon: LightSleetShowersPolarTwilight,
    title: 'Lätt snöblandat regn',
    id: '42m',
  },
  lightsnow: { Icon: LightSnow, title: 'Lite snö', id: '49' },
  lightsnowandthunder: {
    Icon: LightSnowAndThunder,
    title: 'Lite snö och åska',
    id: '33',
  },
  lightsnowshowers_day: {
    Icon: LightSnowShowersDay,
    title: 'Lite snö',
    id: '44d',
  },
  lightsnowshowers_night: {
    Icon: LightSnowShowersNight,
    title: 'Lite snö',
    id: '44n',
  },
  lightsnowshowers_polartwilight: {
    Icon: LightSnowShowersPolarTwilight,
    title: 'Lite snö',
    id: '44m',
  },
  lightssleetshowersandthunder_day: {
    Icon: LightSleetShowersAndThunderDay,
    title: 'Lite snöblandade regnskurar och åska',
    id: '26d',
  },
  lightssleetshowersandthunder_night: {
    Icon: LightSleetShowersAndThunderNight,
    title: 'Lite snöblandade regnskurar och åska',
    id: '26n',
  },
  lightssleetshowersandthunder_polartwilight: {
    Icon: LightSleetShowersAndThunderPolarTwilight,
    title: 'Lite snöblandade regnskurar och åska',
    id: '26m',
  },
  lightssnowshowersandthunder_day: {
    Icon: LightSnowShowersAndThunderDay,
    title: 'Lite snö och åska',
    id: '28d',
  },
  lightssnowshowersandthunder_night: {
    Icon: LightSnowShowersAndThunderNight,
    title: 'Lite snö och åska',
    id: '28n',
  },
  lightssnowshowersandthunder_polartwilight: {
    Icon: LightSnowShowersAndThunderPolarTwilight,
    title: 'Lite snö och åska',
    id: '28m',
  },
  partlycloudy_day: {
    Icon: PartlyCloudyDay,
    title: 'Delvis monligt',
    id: '03d',
  },
  partlycloudy_night: {
    Icon: PartlyCloudyNight,
    title: 'Delvis monligt',
    id: '03n',
  },
  partlycloudy_polartwilight: {
    Icon: PartlyCloudyPolarTwilight,
    title: 'Delvis molnigt under polarskymning',
    id: '03m',
  },
  rain: { Icon: Rain, title: 'Regn', id: '09' },
  rainandthunder: { Icon: RainAndThunder, title: 'Regn och åska', id: '22' },
  rainshowers_day: { Icon: RainShowersDay, title: 'Regn och åska', id: '05d' },
  rainshowers_night: { Icon: RainShowersNight, title: 'Regnigt', id: '05n' },
  rainshowers_polartwilight: {
    Icon: RainShowersPolarTwilight,
    title: 'Regnskurar',
    id: '05m',
  },
  rainshowersandthunder_day: {
    Icon: RainShowersAndThunderDay,
    title: 'Regnskurar och åska',
    id: '06d',
  },
  rainshowersandthunder_night: {
    Icon: RainShowersAndThunderNight,
    title: 'Regnskurar och åska',
    id: '06n',
  },
  rainshowersandthunder_polartwilight: {
    Icon: RainShowersAndThunderPolarTwilight,
    title: 'Regnskurar och åska',
    id: '06m',
  },
  sleet: { Icon: Sleet, title: 'Snöblandet regn', id: '12' },
  sleetandthunder: {
    Icon: SleetAndThunder,
    title: 'Snöblandet regn och åska',
    id: '23',
  },
  sleetshowers_day: {
    Icon: SleetShowersDay,
    title: 'Snöblandet regn',
    id: '07d',
  },
  sleetshowers_night: {
    Icon: SleetShowersNight,
    title: 'Snöblandet regn',
    id: '07n',
  },
  sleetshowers_polartwilight: {
    Icon: SleetShowersPolarTwilight,
    title: 'Snöblandet regn',
    id: '07m',
  },
  sleetshowersandthunder_day: {
    Icon: SleetShowersAndThunderDay,
    title: 'Snöblandet regn och åska',
    id: '20d',
  },
  sleetshowersandthunder_night: {
    Icon: SleetShowersAndThunderNight,
    title: 'Snöblandet regn och åska',
    id: '20n',
  },
  sleetshowersandthunder_polartwilight: {
    Icon: SleetShowersAndThunderPolarTwilight,
    title: 'Snöblandet regn och åska',
    id: '20m',
  },
  snow: { Icon: Snow, title: 'Snö', id: '13' },
  snowandthunder: { Icon: SnowAndThunder, title: 'Snö och åska', id: '14' },
  snowshowers_day: { Icon: SnowShowersDay, title: 'Mycket snö', id: '08d' },
  snowshowers_night: { Icon: SnowShowersNight, title: 'Mycket snö', id: '08n' },
  snowshowers_polartwilight: {
    Icon: SnowShowersPolarTwilight,
    title: 'Mycket snö',
    id: '08m',
  },
  snowshowersandthunder_day: {
    Icon: SnowShowersAndThunderDay,
    title: 'Mycket snö och åska',
    id: '21d',
  },
  snowshowersandthunder_night: {
    Icon: SnowShowersAndThunderNight,
    title: 'Mycket snö och åska',
    id: '21n',
  },
  snowshowersandthunder_polartwilight: {
    Icon: SnowShowersAndThunderPolarTwilight,
    title: 'Mycket snö och åska',
    id: '21m',
  },
}

export default weatherIcons
